name: jsonplaceholder-integration

on:
  push:
    branches:
      - main
      - "feat/*"
  pull_request:
    branches:
      - main

jobs:
  speq-jsonplaceholder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: speq-tms/speq-github-runner@main
        with:
          mode: run
          speq-root: test-repo-mode-jsonplaceholder
          env: ci
          artifacts-prefix: speq-jsonplaceholder
          allure-dir: test-repo-mode-jsonplaceholder/reports/allure
          summary-output: test-repo-mode-jsonplaceholder/reports/results/summary.json
          upload-artifacts: "true"
